name=LaskakitZivyobrazClient
version=0.1.0
author=Patrik Novak
mantainer=Patrik Novak
sentence=Client for zivyobraz.eu
paragraph=Fetches images from zivyobraz.eu. Use with esp32.
category=Communication
url=https://github.com/LaskaKit/laskakit_zivyobraz_client
architectures=*
includes=laskakit_zivyobraz.hpp
